version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    volumes:
      - ./backend:/app
    networks:
      semiconnet:
        ipv4_address: 172.20.0.2
    depends_on:
      - redis
      - ollama
    environment:
      - REDIS_URL=redis://172.20.0.3:6379
      - OLLAMA_URL=http://172.20.0.4:11434

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      semiconnet:
        ipv4_address: 172.20.0.3

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "ollama pull llama3:8b-instruct-q4_K_M && ollama serve"
    networks:
      semiconnet:
        ipv4_address: 172.20.0.4

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./frontend:/app
    networks:
      semiconnet:
        ipv4_address: 172.20.0.5

volumes:
  redis-data:
  ollama-data:

networks:
  semiconnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/29 # Changed subnet to avoid conflict
